name: 发布

on:
  workflow_dispatch:
    # inputs:
    #   target_task:
    #     description: "选择要执行的任务" # 下拉菜单标题
    #     required: true
    #     type: choice
    #     options:
    #       - label: "仅插件" # 显示在下拉菜单中的名称
    #         value: "release_addon" # 实际传递的值
    #       - label: "仅客户端"
    #         value: "release_client"
    #       - label: "全部"
    #         value: "release_all"
  push:
    tags: ["*"]
  #   branches:
  #     - main
  # schedule:
  #   # 每天的UTC时间16:10运行
  #   - cron: '10 16 * * *'

env:
  # 环境变量
  # VERSION_NAME: Amagate-${{ github.ref_name }}
  PRERELEASE: 0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write # 为 GITHUB_TOKEN 设置内容写入权限

jobs:
  release:
    # if: ${{ github.event.inputs.target_task =='release_addon' }}
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 打包
        # if: ${{ github.event.inputs.target_task =='release_addon' || github.event.inputs.target_task =='release_all' }}
        run: |
          # 创建一个包含文件的 zip 文件，排除掉特定文件或文件夹
          cd src/Amagate

          mkdir -p textures
          mkdir -p textures/panorama

          curl -L -o textures/panorama/Marakamda.jpg https://raw.githubusercontent.com/Sryml/Image/refs/heads/master/AG/Marakamda.jpg
          curl -L -o textures/test.bmp https://raw.githubusercontent.com/Sryml/Image/refs/heads/master/AG/test.bmp
          curl -L -o textures/lisa.bmp https://raw.githubusercontent.com/Sryml/Image/refs/heads/master/AG/lisa.bmp
          curl -L -o textures/long.bmp https://raw.githubusercontent.com/Sryml/Image/refs/heads/master/AG/long.bmp

          cp -r ../../docs ./docs
          cp -p ../../README.md README.md
          cp -p ../../LICENSE LICENSE

          # echo ${{ github.ref_name }} > version
          VERSION=$(head -n 1 version | tr -d '\r\n')
          [[ "${VERSION:0:3}" != "dev" ]] && rm -f DEBUG || echo "PRERELEASE=1" >> $GITHUB_ENV
          VERSION_NAME="Amagate-${VERSION}"
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

          cd ..
          zip -r ../${VERSION_NAME}.zip ./Amagate -x "__pycache__/*" "*.tmp" "*.ai"

      # - name: Upload zip file as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ env.VERSION_NAME }}
      #     path: ${{ env.VERSION_NAME }}.zip

      - name: 创建GitHub发布
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          # name: "${{ env.VERSION_NAME }}"
          body: ""
          draft: false
          prerelease: ${{ env.PRERELEASE == 1 }}

      - name: 上传发布资源
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.VERSION_NAME }}.zip
          asset_name: ${{ env.VERSION_NAME }}.zip
          asset_content_type: application/zip
