name: 发布

# Amagate-dev-20240101-0000-abcdef
# for /f "delims=" %i in ('git rev-parse --short HEAD') do set TAG_NAME=dev-%date:~0,4%%date:~5,2%%date:~8,2%-%time:~0,2%%time:~3,2%-%i
# git tag %TAG_NAME%
# git push origin %TAG_NAME%

on:
  workflow_dispatch:
  push:
    tags:
      - "*" # 匹配所有 Tag
  #   branches:
  #     - main
  # schedule:
  #   # 每天的UTC时间16:10运行
  #   - cron: '10 16 * * *'

env:
  # 环境变量
  VERSION_NAME: Amagate-${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write # 为 GITHUB_TOKEN 设置内容写入权限

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: Create a zip file excluding certain files
        run: |
          # 创建一个包含文件的 zip 文件，排除掉特定文件或文件夹
          cd src/Amagate
          mkdir -p textures
          curl -L -o textures/test.bmp https://raw.githubusercontent.com/Sryml/Image/refs/heads/master/AG/test.bmp
          cp ../../README.md README.md
          cp ../../LICENSE LICENSE
          zip -r ../../$VERSION_NAME.zip ./ -x "__pycache__/*" "*.tmp" "*.ai"

      # - name: Upload zip file as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ env.VERSION_NAME }}
      #     path: ${{ env.VERSION_NAME }}.zip

      - name: 创建GitHub发布
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "${{ env.VERSION_NAME }}"
          body: ""
          draft: false
          prerelease: true

      - name: 上传发布资源
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.VERSION_NAME }}.zip
          asset_name: ${{ env.VERSION_NAME }}.zip
          asset_content_type: application/zip
